services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEBHOOK_CONTACT_FORM=ciaociao
      - TURBO_TELEMETRY_DISABLED=1
      - DO_NOT_TRACK=1
    restart: unless-stopped
    # Mount the data directory to persist the SQLite database
    volumes:
      - ./data:/app/data
